name: Release Rust Binary

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: cargo build --release --manifest-path rust-cache-warmer/Cargo.toml

      - name: Rename binary for release asset
        run: mv rust-cache-warmer/target/release/rust-cache-warmer rust-cache-warmer-linux-amd64

      - name: Create GitHub Release and upload binary
        uses: softprops/action-gh-release@v1
        with:
          # This will upload the file created in the previous step.
          files: rust-cache-warmer-linux-amd64 