name: Release Rust Binary

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libaio-dev liburing-dev

      - name: Build release binary with all features
        run: cargo build --release --manifest-path rust-cache-warmer/Cargo.toml

      - name: Build release binary with debug symbols
        run: cargo build --profile profiling --manifest-path rust-cache-warmer/Cargo.toml

      - name: Rename binaries for release assets
        run: |
          mv rust-cache-warmer/target/release/rust-cache-warmer rust-cache-warmer-linux-amd64
          mv rust-cache-warmer/target/profiling/rust-cache-warmer rust-cache-warmer-linux-amd64-profiling

      - name: Create GitHub Release and upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rust-cache-warmer-linux-amd64
            rust-cache-warmer-linux-amd64-profiling 