name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libaio-dev liburing-dev
    - name: Build
      run: cd disk-warmer && make
    - name: Run tests
      run: cd disk-warmer && make test 